### ISSUE TITLE
Hej!

### ISSUE THREAD

**Issue by saraervik** [mewmew/hallondricka#2]
Hej på dig,

Jag ser att du är inne här ofta och tänker att det kanske är bästa kontaktvägen till dig?
Eventgruppen från årets studs försöker stämma träff men kunde inte få tag på dig på telefon. Jag bad Karolin skriva till dig på din kth mail. Förstår att du inte vill skriva ut ditt nummer här men du kanske kan tala om hur man når dig på bäst sätt? 😊 

/Sara

P.S Om inte denna kommunikationskanal fungerar kommer jag att prova röksignaler 😉

**Comment by mewmew** [comment]
Tja Sara!

Haha, du har rätt. GitHub är bästa kommunikationskanalen, näst efter röksignaler så klart ;)

Jag är i Korea fram till i höst så om ni träffas i eventgruppen ge alla en kram från mig :)

*glada kramar*
Robin

P.S. det går bra att skicka till min kth-mail också :) Jag tror inte jag sett Karolins e-mail, men kan ha missat det. Ska kolla igen.

**Comment by saraervik** [comment]
Vad kul att höra från dig! Nu minns jag att du skulle på utbytestermin.
Hoppas att du har det fantastiskt och jag hälsar alla så mycket från dig :)
